"""empty message

Revision ID: 10e02f80161a
Revises: c5624eea2a6b
Create Date: 2022-04-15 11:26:29.563713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e02f80161a'
down_revision = 'c5624eea2a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('logo', sa.String(), nullable=True))
    op.add_column('contents', sa.Column('banner', sa.String(), nullable=True))
    op.add_column('contents', sa.Column('background_picture', sa.String(), nullable=True))
    op.alter_column('contents', 'thumbnail',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contents', 'thumbnail',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('contents', 'background_picture')
    op.drop_column('contents', 'banner')
    op.drop_column('contents', 'logo')
    # ### end Alembic commands ###
