"""empty message

Revision ID: 7a9df107e801
Revises: 10e02f80161a
Create Date: 2022-04-15 14:17:42.143039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9df107e801'
down_revision = '10e02f80161a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
